version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=develop
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6.8-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=os